# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dsptask.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dsptask.proto',
  package='tutorial',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rdsptask.proto\x12\x08tutorial\"D\n\x0cOpParseParam\x12\r\n\x05netID\x18\x01 \x02(\x05\x12\x11\n\tcbJsonStr\x18\x02 \x01(\t\x12\x12\n\nusrJsonStr\x18\x03 \x01(\t\"[\n\rOpFInferParam\x12\x11\n\tnetworkID\x18\x01 \x01(\x05\x12\x12\n\ncallbackID\x18\x02 \x01(\x05\x12\x10\n\x08tensorIn\x18\x03 \x01(\x0c\x12\x11\n\ttensorOut\x18\x04 \x01(\x0c\"\xa4\x01\n\x0c\x43\x61llbackData\x12&\n\x07\x63mdType\x18\x01 \x02(\x0e\x32\x15.tutorial.CommandType\x12\x0e\n\x06status\x18\x02 \x01(\x05\x12,\n\x0copParseParam\x18\x03 \x01(\x0b\x32\x16.tutorial.OpParseParam\x12.\n\ropFInferParam\x18\x04 \x01(\x0b\x32\x17.tutorial.OpFInferParam*v\n\x0b\x43ommandType\x12\x0b\n\x07\x43mdNone\x10\x00\x12\x10\n\x0c\x43mdHeartBeat\x10\x01\x12\x0f\n\x0b\x43mdOpFInfer\x10\x02\x12\x12\n\x0e\x43mdOpFInferAck\x10\x03\x12\x0f\n\x0b\x43mdShutDown\x10\x04\x12\x12\n\x0e\x43mdShutDownAck\x10\x05'
)

_COMMANDTYPE = _descriptor.EnumDescriptor(
  name='CommandType',
  full_name='tutorial.CommandType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CmdNone', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CmdHeartBeat', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CmdOpFInfer', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CmdOpFInferAck', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CmdShutDown', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CmdShutDownAck', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=357,
  serialized_end=475,
)
_sym_db.RegisterEnumDescriptor(_COMMANDTYPE)

CommandType = enum_type_wrapper.EnumTypeWrapper(_COMMANDTYPE)
CmdNone = 0
CmdHeartBeat = 1
CmdOpFInfer = 2
CmdOpFInferAck = 3
CmdShutDown = 4
CmdShutDownAck = 5



_OPPARSEPARAM = _descriptor.Descriptor(
  name='OpParseParam',
  full_name='tutorial.OpParseParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='netID', full_name='tutorial.OpParseParam.netID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cbJsonStr', full_name='tutorial.OpParseParam.cbJsonStr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='usrJsonStr', full_name='tutorial.OpParseParam.usrJsonStr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=95,
)


_OPFINFERPARAM = _descriptor.Descriptor(
  name='OpFInferParam',
  full_name='tutorial.OpFInferParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='networkID', full_name='tutorial.OpFInferParam.networkID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='callbackID', full_name='tutorial.OpFInferParam.callbackID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tensorIn', full_name='tutorial.OpFInferParam.tensorIn', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tensorOut', full_name='tutorial.OpFInferParam.tensorOut', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=188,
)


_CALLBACKDATA = _descriptor.Descriptor(
  name='CallbackData',
  full_name='tutorial.CallbackData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmdType', full_name='tutorial.CallbackData.cmdType', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='tutorial.CallbackData.status', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='opParseParam', full_name='tutorial.CallbackData.opParseParam', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='opFInferParam', full_name='tutorial.CallbackData.opFInferParam', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=355,
)

_CALLBACKDATA.fields_by_name['cmdType'].enum_type = _COMMANDTYPE
_CALLBACKDATA.fields_by_name['opParseParam'].message_type = _OPPARSEPARAM
_CALLBACKDATA.fields_by_name['opFInferParam'].message_type = _OPFINFERPARAM
DESCRIPTOR.message_types_by_name['OpParseParam'] = _OPPARSEPARAM
DESCRIPTOR.message_types_by_name['OpFInferParam'] = _OPFINFERPARAM
DESCRIPTOR.message_types_by_name['CallbackData'] = _CALLBACKDATA
DESCRIPTOR.enum_types_by_name['CommandType'] = _COMMANDTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OpParseParam = _reflection.GeneratedProtocolMessageType('OpParseParam', (_message.Message,), {
  'DESCRIPTOR' : _OPPARSEPARAM,
  '__module__' : 'dsptask_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.OpParseParam)
  })
_sym_db.RegisterMessage(OpParseParam)

OpFInferParam = _reflection.GeneratedProtocolMessageType('OpFInferParam', (_message.Message,), {
  'DESCRIPTOR' : _OPFINFERPARAM,
  '__module__' : 'dsptask_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.OpFInferParam)
  })
_sym_db.RegisterMessage(OpFInferParam)

CallbackData = _reflection.GeneratedProtocolMessageType('CallbackData', (_message.Message,), {
  'DESCRIPTOR' : _CALLBACKDATA,
  '__module__' : 'dsptask_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.CallbackData)
  })
_sym_db.RegisterMessage(CallbackData)


# @@protoc_insertion_point(module_scope)
