interface=wlan0
driver=nl80211
ctrl_interface=/var/hostapd
ssid=go
channel=1
#ieee80211n=1
hw_mode=g
ignore_broadcast_ssid=0
wpa=2
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
wpa_passphrase=12345678


