##### wpa_supplicant configuration file template #####
ctrl_interface=/var/wpa_supplicant
update_config=1
eapol_version=1
ap_scan=1
fast_reauth=1

network={
	ssid="Artosyn-AP"
	psk="Welcome2Artosyn"
}
