git rm -f arsdk/platforms/rootfs/busybox/busybox-1.25.0/archival/Config.in
git rm -f arsdk/platforms/rootfs/busybox/busybox-1.25.0/archival/Kbuild
git rm -f arsdk/platforms/rootfs/busybox/busybox-1.25.0/include/applets.h
git rm -f arsdk/platforms/rootfs/busybox/busybox-1.25.0/include/bbconfigopts.h
git rm -f arsdk/platforms/rootfs/busybox/busybox-1.25.0/include/bbconfigopts_bz2.h
git rm -f arsdk/platforms/rootfs/busybox/busybox-1.25.0/include/usage.h
git rm -f arsdk/platforms/rootfs/busybox/busybox-1.25.0/loginutils/Config.in
git rm -f arsdk/platforms/rootfs/busybox/busybox-1.25.0/loginutils/Kbuild
git rm -f arsdk/platforms/rootfs/busybox/busybox-1.25.0/miscutils/Config.in
git rm -f arsdk/platforms/rootfs/busybox/busybox-1.25.0/miscutils/Kbuild
