#ifndef ICCPORT_H
#define ICCPORT_H
#include "Uart.h"
#include "SystemIO.h"
#include <errno.h>
#include <stddef.h>
#include "ThreadSynchronization.h"

#define EAGAIN (11)
#define ENOMEM (12)
#define EINVAL (22)    /* Invalid argument */
#define EOVERFLOW (75) /* Invalid argument */
#define ETIME (62)
#define osWaitForever 0xFFFFFFFFU ///< Wait forever timeout value.
#define PRN_UART (0)

typedef enum
{
    osFlagsWaitNone = -1,
    osFlagsWaitint,
    osFlagsWaitStatus
} flag_wait_status_e;

// Flags options (\ref osThreadFlagsWait and \ref osEventFlagsWait).
#define osFlagsWaitAny 0x00000000U ///< Wait for any flag (default).
#define osFlagsWaitAll 0x00000001U ///< Wait for all flags.
#define osFlagsNoClear 0x00000002U ///< Do not clear flags which have been specified to wait for.
//#define portTICK_PERIOD_MS (10000)

// Flags errors (returned by osThreadFlagsXxxx and osEventFlagsXxxx).
#define osFlagsError 0x80000000U          ///< Error indicator.
#define osFlagsErrorUnknown 0xFFFFFFFFU   ///< osError (-1).
#define osFlagsErrorTimeout 0xFFFFFFFEU   ///< osErrorTimeout (-2).
#define osFlagsErrorResource 0xFFFFFFFDU  ///< osErrorResource (-3).
#define osFlagsErrorParameter 0xFFFFFFFCU ///< osErrorParameter (-4).
#define osFlagsErrorISR 0xFFFFFFFAU       ///< osErrorISR (-6).

// Thread attributes (attr_bits in \ref osThreadAttr_t).
#define osThreadDetached 0x00000000U ///< Thread created in detached mode (default)
#define osThreadJoinable 0x00000001U ///< Thread created in joinable mode

// Mutex attributes (attr_bits in \ref osMutexAttr_t).
#define osMutexRecursive 0x00000001U   ///< Recursive mutex.
#define osMutexPrioInherit 0x00000002U ///< Priority inherit protocol.
#define osMutexRobust 0x00000008U      ///< Robust mutex.

//#define malloc PortMallocExternal
#define pdFALSE (0)
#define pdTRUE (1)

#define ALIGN(m, n) ((m + n - 1) & (~(n - 1)))

/// Status code values returned by CMSIS-RTOS functions.
typedef enum
{
    osOK = 0,                     ///< Operation completed successfully.
    osError = -1,                 ///< Unspecified RTOS error: run-time error but no other error message fits.
    osErrorTimeout = -2,          ///< Operation not completed within the timeout period.
    osErrorResource = -3,         ///< Resource not available.
    osErrorParameter = -4,        ///< Parameter error.
    osErrorNoMemory = -5,         ///< System is out of memory: it was impossible to allocate or reserve memory for the operation.
    osErrorISR = -6,              ///< Not allowed in ISR context: the function cannot be called from interrupt service routines.
    osStatusReserved = 0x7FFFFFFF ///< Prevents enum down-size compiler optimization.
} osStatus_t;
typedef long BaseType_t;
typedef BaseType_t (*pdCOMMAND_LINE_CALLBACK)(char *pcWriteBuffer, size_t xWriteBufferLen, const char *pcCommandString);
typedef struct xCOMMAND_LINE_INPUT
{
    const char *const pcCommand;                        /* The command that causes pxCommandInterpreter to be executed.  For example "help".  Must be all lower case. */
    const char *const pcHelpString;                     /* String that describes how to use the command.  Should start with the command itself, and end with "\r\n".  For example "help: Returns a list of all the commands\r\n". */
    const pdCOMMAND_LINE_CALLBACK pxCommandInterpreter; /* A pointer to the callback function that will return the output generated by the command. */
    char cExpectedNumberOfParameters;                   /* Commands expect a fixed number of parameters, which may be zero. */
} CLI_Command_Definition_t;

/// \details Thread ID identifies the thread.
typedef void *osThreadId_t;
typedef unsigned int uint32_t;
typedef int int32_t;
typedef unsigned char uint8_t;
typedef unsigned int portBASE_TYPE;
typedef void *osMutexId_t;
typedef struct
{
    const char *name;   ///< name of the mutex
    uint32_t attr_bits; ///< attribute bits
    void *cb_mem;       ///< memory for control block
    uint32_t cb_size;   ///< size of provided memory for control block
} osMutexAttr_t;

#ifndef AR_ASSERT
#define AR_ASSERT(x)                                                  \
    if (x == 0)                                                       \
    {                                                                 \
        debug_print("assert line %d, file %s\n", __LINE__, __FILE__); \
        *((unsigned int *)(0x00000000)) = 0;                          \
        while (1)                                                     \
            ;                                                         \
    }
#endif

extern osMutexId_t osMutexNew(const osMutexAttr_t *attr);
extern int osMutexAcquire(osMutexId_t mutex, int flag);
extern int osThreadFlagsSet(osThreadId_t thread, int flag);
extern int osMutexRelease(osMutexId_t mutex);
extern int osThreadGetId();
extern int xDbgPrintf(int uart, const char *fmt, ...);
extern int osThreadFlagsSet(osThreadId_t owner, int32_t flag);
extern int osThreadFlagsWait(int flag, int32_t wait_status, int32_t opt);
extern int osThreadFlagsClear(int32_t flag);
#endif /* ICC_PORT_H */
