#ModelName=ModelPath
MobileNetSSDModel=/usrdata/usr/data/arstack/ssd-face-05.cdnnQdata
MobileNetModel=/usrdata/usr/data/arstack/age-gender.cdnnQdata
ONetModel21=/usrdata/usr/data/arstack/onet21.cdnnQdata
ONetModel5=/usrdata/usr/data/arstack/onet.cdnnQdata
LightFaceModel=/usrdata/usr/data/arstack/face-96-112.cdnnQdata
