#make BOOT_MEDIA=emmc BASE_BOARD=zam210 BUILD_TYPE=debug APP=ipcam CHIP=ar9341 SEC_BOOT=n MPP_SERVICE=app all -j 4
make BOOT_MEDIA=emmc BASE_BOARD=kog010 BUILD_TYPE=debug APP=ipcam CHIP=ar9341 SEC_BOOT=n MPP_SERVICE=app all -j 4
