ifeq ($(PARAM_FILE), )
     PARAM_FILE:=../../../../../arsdk/Makefile.param
     include $(PARAM_FILE)
endif
STATIC_LIBRARY = libsns_os04a10.a
SHARED_LIBRARY = libsns_os04a10.so

# Define files
#------------------------------------------

SRCDIRS   = ./

INSTALL_HEADERS := 

# Define flags
#------------------------------------------

CFLAGS    += -I./  -I../

#LOCAL_LIB =
# Include make rule file
#------------------------------------------
include ../../../usr_lib_rules.mk


