# this file contains the default setting in factory partition
# PLEASE TAKE CARE IF YOU WANT TO MODIFY THE PARAMETER !!!
# pleae add to corresponding module part and update the script if necessary
#

# common
kern_log_level	1

# network
nw_itf_name		eth0

# mac
nw_itf_mac		aa:bb:cc:dd:ee:ff
