ifeq ($(PARAM_FILE), )
     PARAM_FILE:=../../../../../arsdk/Makefile.param
     include $(PARAM_FILE)
endif
STATIC_LIBRARY = libpn_tp2803.a
SHARED_LIBRARY = libpn_tp2803.so

# Define files
#------------------------------------------

SRCDIRS   = ./

INSTALL_HEADERS := 

# Define flags
#------------------------------------------

CFLAGS    += -I./

#LOCAL_LIB =
# Include make rule file
#------------------------------------------
include ../../../usr_lib_rules.mk


