// xm6elftool.cpp : 定义控制台应用程序的入口点。
//

#include "stdafx.h"
#include <string.h>
#include <malloc.h>
#include <errno.h>
#include <fcntl.h>
#include <stdlib.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>

#define __LIBELF_INTERNAL__ 1
#include "libelf.h"
#include "common_list.h"
#include "dsp_bin_pack.h"

#define ARXM6_PTCM_NAME "./C0.bin"
#define ARXM6_DTCM_NAME "./D0.bin"
#define ARXM6_EXTC_NAME "./C1.bin"
#define ARXM6_EXTD_NAME "./D1.bin"

#define ARXM6_BIN_NAME "./ceva.bin"

#define ALIGNED(x,align) ( (x)%align == 0 ? (x) : ( ( (x)/align + 1 ) * align ) )
//
//typedef enum
//{
//	ARXM6_SEGMENT_PTCM = 1,
//	ARXM6_SEGMENT_DTCM = 2,
//	ARXM6_SEGMENT_EXT_CODE = 3,
//	ARXM6_SEGMENT_EXT_DATA = 4,
//	ARXM6_SEGMENT_MAX
//} E_ARXM6_SEGMENT_TYPE;
//
//typedef struct 
//{
//	unsigned int uiType; //segment type: dtcm, ptcm, 
//	unsigned int uiAddr; //Physical addr of this segment
//	unsigned int uiLen;
//	char strBinFileName[FILENAME_MAX]; //section to bin file generated by objcopy -j -O binary
//} stArXM6SectionBinary;
//
//stArXM6SectionBinary secBins[32]; //all sections info are stored here and put them into a list.
//
//list_st gListPtcmSecBin, gListDtcmSecBin, gListExtCSecBin, gListExtDSecBin;

typedef struct
{
	char strPtcmFileName[FILENAME_MAX];
	char strDtcmFileName[FILENAME_MAX];
	char strExtCFileName[FILENAME_MAX];
	char strExtDFileName[FILENAME_MAX];
	char strFinalFileName[FILENAME_MAX];
	unsigned int uiPtcmStartAddr;
	unsigned int uiDtcmStartAddr;
	unsigned int uiExtCStartAddr;
	unsigned int uiExtDStartAddr;

} stDSPPackBin;

void print_usage(char * name)
{
	printf("\n%s usage:\n", name);
	printf("%s [XM6 ELF file name]\n", name);
}

void save_binary_to_file(char * filename, char * data, int len)
{
	char * tmp = data;

	if (!filename)
	{
		printf("Invalid filename!\n");
		return;
	}
	FILE * fp = fopen(filename, "ab+");
	if (!fp)
	{
		printf("Open file %s failed!\n", filename);
		return;
	}

	//if data is NULL, which means NOLOAD/NOBITS , write 0 to file
	if (!tmp)
	{
		tmp = (char *)malloc(len);
		if (!tmp)
		{
			printf("Malloc tmp failed\n");
			fclose(fp);
			return;
		}
		memset(tmp, 0, len);
	}

	fwrite(tmp, 1, len, fp);
	fclose(fp);

	return;

}

int pack_binary(stDSPPackBin * pstDSPPackBin)
{
	dsp_bin dsp_bin1(1024 * 1024 * 10,
		pstDSPPackBin->strPtcmFileName,
		pstDSPPackBin->strDtcmFileName,
		pstDSPPackBin->strExtCFileName,
		pstDSPPackBin->strExtDFileName,
		pstDSPPackBin->strFinalFileName,
		pstDSPPackBin->uiPtcmStartAddr,
		pstDSPPackBin->uiDtcmStartAddr,
		pstDSPPackBin->uiExtCStartAddr,
		pstDSPPackBin->uiExtDStartAddr,
		0);

	dsp_bin1.dsp_pack();
	dsp_bin1.add_header_to_img();
	
	return 0;
}
//Get XM6 ELF file and translate to bin file
int main(int argc, char * argv[])
{
	char strElfFileName[FILENAME_MAX] = { 0 };
	char strDTCMFileName[FILENAME_MAX] = { 0 };
	char strPTCMFileName[FILENAME_MAX] = { 0 };
	char strExtDFileName[FILENAME_MAX] = { 0 };
	char strExtCFileName[FILENAME_MAX] = { 0 };
	FILE * fpElf = NULL;
	int iElfFd = 0;

	if (argc <= 1)
	{
		print_usage((char *)argv[0]);
		return -1;
	}
	//printf("ARGs : %s\n", argv[1]);

	//Read xm6 elf file
	strncpy(strElfFileName, (char *)argv[1], FILENAME_MAX);

	fpElf = fopen(strElfFileName, "rb");
	if (!fpElf)
	{
		printf("Open ELF file error!\n");
		return -1;
	}
	fseek(fpElf, 0, SEEK_END);
	int iElfLen = ftell(fpElf);
	rewind(fpElf);

	if (iElfLen < 1)
	{
		printf("This ELF %s is a null file.\n", strElfFileName);
		fclose(fpElf);
		return -1;
	}

	char * chpElfBuff = (char *)malloc(iElfLen);
	if (!chpElfBuff)
	{
		printf("Malloc failed!\n");
		fclose(fpElf);
		return -1;
	}

	int readLen = fread(chpElfBuff, 1, iElfLen, fpElf);
	if (readLen != iElfLen)
	{
		printf("Read ELF error: %s\n", strerror(errno));
		free(chpElfBuff);
		fclose(fpElf);
		return -1;
	}
	fclose(fpElf);

	//Call libelf to read section headers and objcopy the binaries
	if (elf_version(EV_CURRENT) == EV_NONE) 
	{
		printf("Elf library out of date\n");
		free(chpElfBuff);
		return -1;
	}

	Elf * pElf = elf_memory(chpElfBuff, iElfLen);
	if (!pElf)
	{
		printf("Get ELF handle error!\n");
		free(chpElfBuff);
		return -1;
	}

	//check if elf is the right type
	if (elf_kind(pElf) != ELF_K_ELF)
	{
		printf("Unexpected ELF type!\n");
		elf_end(pElf);
		free(chpElfBuff);
		return -1;		
	}

	Elf32_Ehdr * pEhdr32 = elf32_getehdr(pElf);
	Elf64_Ehdr * pEhdr64 = elf64_getehdr(pElf);
	if (!pEhdr32 && !pEhdr64)
	{
		printf("Unable to get machine ID from ELF\n");
		elf_end(pElf);
		free(chpElfBuff);
		return -1;
	}

	int iMachineId = 0;
	if (pEhdr32 && !pEhdr64)
	{
		iMachineId = pEhdr32->e_machine;
	}
	else
	{
		iMachineId = pEhdr64->e_machine;
	}

	printf("ELF %s MachineID %d\n", strElfFileName, iMachineId);

	strcpy(strPTCMFileName, ARXM6_PTCM_NAME);
	strcpy(strDTCMFileName, ARXM6_DTCM_NAME);
	strcpy(strExtCFileName, ARXM6_EXTC_NAME);
	strcpy(strExtDFileName, ARXM6_EXTD_NAME);

	//delete the old files
	remove(strPTCMFileName);
	remove(strDTCMFileName);
	remove(strExtCFileName);
	remove(strExtDFileName);

	//loop all sections and retrieve that 'AX' to code and 'WA' to data
	//Only take care of ELF32 format

	Elf_Scn * section = NULL;
	char * strBinFileName = NULL;
	unsigned int uiPtcmStartAddr = 0, uiPtcmFind = 0;
	unsigned int uiDtcmStartAddr = 0, uiDtcmFind = 0;
	unsigned int uiExtCStartAddr = 0, uiExtCFind = 0;
	unsigned int uiExtDStartAddr = 0, uiExtDFind = 0;
	char *section_datainternal = ".data.internal";//in 9301,only .data.internal & .data.external load to bin
	char *section_dataexternal = ".data.external";


	while ((section = elf_nextscn(pElf, section)) != NULL)
	{
		Elf32_Shdr * shdr = elf32_getshdr(section);
		if (shdr)
		{
			const char * name = elf_strptr(pElf, pEhdr32->e_shstrndx, shdr->sh_name);

			//PTCM: addr < 0x30000000 and has 'X' flags
			if (shdr->sh_addr < 0x30000000 && (shdr->sh_flags & SHF_EXECINSTR))
			{
				strBinFileName = strPTCMFileName;
				if (uiPtcmFind == 0)
				{
					uiPtcmStartAddr = shdr->sh_addr;
					uiPtcmFind = 1;
					printf("PTCM start from 0x%x\n", uiPtcmStartAddr);
				}
			}
			else if (shdr->sh_addr < 0x30000000 && ( (shdr->sh_flags & SHF_EXECINSTR) == 0) 
				&& (shdr->sh_flags & SHF_ALLOC) ) //DTCM
			{
				if (!strcmp(name, section_datainternal))
				{
					strBinFileName = strDTCMFileName;
					if (uiDtcmFind == 0)
					{
						uiDtcmStartAddr = shdr->sh_addr;
						uiDtcmFind = 1;
						printf("DTCM start from 0x%x\n", uiDtcmStartAddr);
					}
				}
				else
				{
					continue;
				}
			}
			else if (shdr->sh_addr >= 0x30000000 && (shdr->sh_flags & SHF_EXECINSTR)) //ext code
			{
				strBinFileName = strExtCFileName;
				if (uiExtCFind == 0)
				{
					uiExtCStartAddr = shdr->sh_addr;
					uiExtCFind = 1;
					printf("Ext code start from 0x%x\n", uiExtCStartAddr);
				}
			}
			else if (shdr->sh_addr >= 0x30000000 && ( (shdr->sh_flags & SHF_EXECINSTR) == 0)
				&& (shdr->sh_flags & SHF_ALLOC))
			{
				if (!strcmp(name, section_dataexternal))
				{ 
					strBinFileName = strExtDFileName;
					if (uiExtDFind == 0)
					{
						uiExtDStartAddr = shdr->sh_addr;
						uiExtDFind = 1;
						printf("Ext data start from 0x%x\n", uiExtDStartAddr);
					}
				}
				else
				{
					continue;
				}
			}
			else
			{
				//printf("This layer is no need to retrieve: %s\n", name);
				continue;
			}

			if (shdr->sh_size == 0) //no rawdata
			{
				continue;
			}				
			
			printf("ELF Section: %s Type 0x%x Addr 0x%x Size 0x%x Flag 0x%x\n", name, shdr->sh_type, shdr->sh_addr, shdr->sh_size, shdr->sh_flags);

			if (shdr->sh_type == SHT_NOBITS)
			{
				save_binary_to_file(strBinFileName, NULL, ALIGNED(shdr->sh_size, shdr->sh_addralign));
			}
			else
			{
				Elf_Data * data = NULL;
				data = elf_rawdata(section, data);
				if (!data || data->d_size == 0 || data->d_buf == 0)
				{
					continue;
				}

				save_binary_to_file(strBinFileName, (char *)data->d_buf, data->d_size);
				//fill with 0 if it's not aligned
				if (data->d_size % shdr->sh_addralign != 0)
				{
					save_binary_to_file(strBinFileName, NULL, ALIGNED(data->d_size, shdr->sh_addralign) - data->d_size);
				}					
			}			

		}
		
	}

	//Merge them into one binary file with artosyn header
	stDSPPackBin packParams = { 0 };
	strcpy(packParams.strPtcmFileName, strPTCMFileName);
	strcpy(packParams.strDtcmFileName, strDTCMFileName);
	strcpy(packParams.strExtCFileName, strExtCFileName);
	strcpy(packParams.strExtDFileName, strExtDFileName);
	strcpy(packParams.strFinalFileName, ARXM6_BIN_NAME);

	packParams.uiPtcmStartAddr = uiPtcmStartAddr;
	packParams.uiDtcmStartAddr = uiDtcmStartAddr;
	packParams.uiExtCStartAddr = uiExtCStartAddr;
	packParams.uiExtDStartAddr = uiExtDStartAddr;

	remove(ARXM6_BIN_NAME); 

	int ret = pack_binary(&packParams);
	if (ret)
	{
		printf("Pack DSP image error! ret = %d\n", ret);
	}
	else
	{
		printf("Pack DSP XM6 image succeed!\n", ret);
	}

	free(chpElfBuff);
	return ret;

}

